- name: Copy pgbouncer config file
  ansible.builtin.template:
    src: /home/node1/ansible/configfiles/pgbouncer.ini
    dest: /etc/pgbouncer/

- name: create file 
  ansible.builtin.file:
    path: /var/run/pgbouncer
    owner: postgres
    group: postgres
    state: directory
