- name: Copy patroni config file
  ansible.builtin.template:
    src: /home/node1/ansible/configfiles/config.yml.j2
    dest: /etc/patroni/config.yml

- name: Remove postgresql.conf file
  file:
    path: /etc/postgresql/14/main/postgresql.conf  
    state: absent

- name: Ensure PostgreSQL data directory exists
  become: yes
  file:
    path: /data/postgresql/16/main
    state: directory
    owner: postgres
    group: postgres
    mode: '0750'


- name: Restart Patroni service
  become: yes
  service:
    name: patroni
    state: restarted

